# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StrategyDesignDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Masonry'
pod 'LMJDropdownMenu'
  # Pods for StrategyDesignDemo

  target 'StrategyDesignDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StrategyDesignDemoUITests' do
    # Pods for testing
  end

end
